### ISSUE TITLE
Please move issues to nf-core fork

### ISSUE THREAD

**Issue by ewels** [nservant/nf-core-hic#8]
Hi @nservant!

Looking great here, but would you mind moving the issues over to nf-core/hic instead please? It's easier to keep track of everything if that's the central point where all discussion is centred.

Once moved it's nice if you can disable issues / wiki / projects etc on your fork and set the description and URL to try to guide people to the main nf-core repo. For an example, see https://github.com/ewels/nf-core-rnaseq

Thanks!

Phil

**Comment by nservant** [comment]
done !
